// Auto-generated by scripts/generate-rulesets.mjs.
// Do not edit manually. Run `pnpm generate` to update.
//
// Error rules from newer ADR versions that are missing in adr-20, exposed
// as warnings so users get advance notice before the rule becomes a hard
// error in a future version. Source rulesets:
//   - https://gitdocumentatie.logius.nl/publicatie/api/adr/2.1.0/media/linter.yaml
//   - https://gitdocumentatie.logius.nl/publicatie/api/adr/2.2.0/media/linter.yaml

import type { HumanReadableDiagnosticSeverity, RuleDefinition } from '@stoplight/spectral-core';
import { pattern, schema, truthy } from '@stoplight/spectral-functions';

export const adr20FutureWarnings: Record<string, RuleDefinition | HumanReadableDiagnosticSeverity> = {
  'oas3-api-servers': 'warn',
  openapi3: {
    severity: 'warn',
    given: ['$.[\'openapi\']'],
    then: {
      function: pattern,
      functionOptions: {
        match: '^3.0.*$',
      },
    },
    message: 'Use OpenAPI Specification for documentation (becomes an error in ADR 2.1)',
  },
  'paths-open-api-json-resource-exists': {
    severity: 'warn',
    given: ['$.paths'],
    then: {
      function: truthy,
      field: '/openapi.json',
    },
    message: 'There does not exist a resource `/openapi.json` that returns the OpenAPI specification document (becomes an error in ADR 2.1)',
  },
  'paths-open-api-json-resource-has-get': {
    severity: 'warn',
    given: ['$.paths[/openapi.json]'],
    then: {
      function: pattern,
      functionOptions: {
        match: 'get',
      },
      field: '@key',
    },
    message: 'There does not exist a GET method (and no other methods) for the `/openapi.json` resource (becomes an error in ADR 2.1)',
  },
  'paths-open-api-json-specify-cors-header': {
    severity: 'warn',
    given: ['$.paths[/openapi.json].get.responses[?(@property && @property.match(/(2|3)\\d\\d/))].headers'],
    then: {
      function: truthy,
      field: 'access-control-allow-origin',
    },
    message: 'The response of the `/openapi.json` resource should set the `access-control-allow-origin` header with value `*` (becomes an error in ADR 2.1)',
  },
  'info-contact': 'warn',
  'info-contact-fields-exist': {
    severity: 'warn',
    given: ['$.info.contact'],
    then: {
      function: schema,
      functionOptions: {
        schema: {
          required: ['email', 'name', 'url'],
        },
      },
    },
    message: 'Missing fields in `info.contact` field. Must specify email, name and url. (becomes an error in ADR 2.1)',
  },
  'path-keys-no-trailing-slash': 'warn',
  'nlgov:openapi-root-exists': {
    severity: 'warn',
    given: '$',
    then: {
      field: 'openapi',
      function: truthy,
    },
    message: 'The root of the document must contain the `openapi` property. (becomes an error in ADR 2.2)',
  },
  'nlgov:paths-kebab-case': {
    severity: 'warn',
    message: '{{property}} is not kebab-case. (becomes an error in ADR 2.2)',
    given: '$.paths[?(@property && !@property.match(/\\/openapi\\.(json)|(yaml)/))]~',
    then: {
      function: pattern,
      functionOptions: {
        match: '^(\\/|(\\/_[a-z0-9]+|\\/(([a-z0-9\\-]+|{[^}]+})(\\/([a-z0-9\\-\\.]+|{[^}]+}))*)(\\/_[a-z]+)?)\\/?)$',
      },
    },
  },
  'nlgov:query-keys-camel-case': {
    severity: 'warn',
    message: '{{value}} is not lower camelCase. (becomes an error in ADR 2.2)',
    given: ['$.paths.*.*.parameters[?(@.in==\'query\')]', '$.components.securitySchemes[?(@.in==\'query\')]'],
    then: {
      function: pattern,
      field: 'name',
      functionOptions: {
        match: '^\\$?[a-z][a-z\\d]*([A-Z][a-z\\d]*)*$',
      },
    },
  },
  'nlgov:use-problem-schema': {
    severity: 'warn',
    message: 'The content type of an error response should be application/problem+json or application/problem+xml to match RFC 9457. (becomes an error in ADR 2.2)',
    given: '$..[responses][?(@property && @property.match(/(4|5)\\d\\d/))].content',
    then: {
      function: schema,
      functionOptions: {
        schema: {
          anyOf: [
            {
              required: ['application/problem+json'],
            },
            {
              required: ['application/problem+xml'],
            },
          ],
        },
      },
    },
  },
  'nlgov:problem-schema-members': {
    severity: 'warn',
    message: '{{error}}. These fields are required: status, title and detail. (becomes an error in ADR 2.2)',
    given: '$..[responses][?(@property && @property.match(/(4|5)\\d\\d/))].content[?(@property=="application/problem+json" || @property=="application/problem+xml")]..schema',
    then: {
      function: schema,
      functionOptions: {
        schema: {
          type: 'object',
          properties: {
            properties: {
              type: 'object',
              required: ['status', 'title', 'detail'],
            },
          },
        },
      },
    },
  },
  'nlgov:problem-invalid-input': {
    severity: 'warn',
    message: 'GET and DELETE endpoints that have parameters, and all other endpoints must be able to return a 400 response (becomes an error in ADR 2.2)',
    given: ['$.paths..[?( @property.match(/(get)|(delete)/) && @.parameters && @.parameters.length > 0 )]', '$.paths..[?( @property.match(/(put)|(post)|(patch)/))]'],
    then: {
      function: schema,
      functionOptions: {
        schema: {
          type: 'object',
          properties: {
            responses: {
              type: 'object',
              required: ['400'],
            },
          },
        },
      },
    },
  },
  'nlgov:date-time-ensure-timezone': {
    severity: 'warn',
    given: '$..properties[*].format',
    message: 'Use date-time format which includes a timezone (becomes an error in ADR 2.2)',
    then: {
      function: pattern,
      functionOptions: {
        notMatch: '/^date-time-local$/',
      },
    },
  },
  'nlgov:time-without-timezone': {
    severity: 'warn',
    given: '$..properties[*].format',
    message: 'Use time-local format without a timezone (becomes an error in ADR 2.2)',
    then: {
      function: pattern,
      functionOptions: {
        notMatch: '/^time$/',
      },
    },
  },
  'nlgov:specify-format-for-date-and-time': {
    severity: 'warn',
    given: ['$..properties[date,datum]', '$..properties[?(@property && @property.match(/((\\w+D)|(_[dD]))((ate)|(atum))/))]'],
    message: 'Any date field must set \'format\' to \'date\' (becomes an error in ADR 2.2)',
    then: {
      function: schema,
      functionOptions: {
        schema: {
          anyOf: [
            {
              required: ['format'],
            },
            {
              properties: {
                allOf: {
                  type: 'array',
                  items: {
                    required: ['format'],
                  },
                },
              },
              required: ['allOf'],
            },
          ],
        },
      },
    },
  },
  'nlgov:use-date-instead-of-datetime': {
    severity: 'warn',
    given: ['$..properties[date,datum]..format', '$..properties[?(@property && @property.match(/((\\w+D)|(_[dD]))((ate)|(atum))/))]..format'],
    message: 'Field represents a date and therefore must set \'format\' to \'date\' (becomes an error in ADR 2.2)',
    then: {
      function: pattern,
      functionOptions: {
        notMatch: '/^date-time$/',
      },
    },
  },
};
