// Auto-generated by scripts/generate-rulesets.mjs.
// Do not edit manually. Run `pnpm generate` to update.
//
// Error rules from newer ADR versions that are missing in adr-21, exposed
// as warnings so users get advance notice before the rule becomes a hard
// error in a future version. Source rulesets:
//   - https://gitdocumentatie.logius.nl/publicatie/api/adr/2.2.0/media/linter.yaml

import type { HumanReadableDiagnosticSeverity, RuleDefinition } from '@stoplight/spectral-core';
import { pattern, schema, truthy } from '@stoplight/spectral-functions';

export const adr21FutureWarnings: Record<string, RuleDefinition | HumanReadableDiagnosticSeverity> = {
  'path-keys-no-trailing-slash': 'warn',
  'nlgov:openapi-root-exists': {
    severity: 'warn',
    given: '$',
    then: {
      field: 'openapi',
      function: truthy,
    },
    message: 'The root of the document must contain the `openapi` property. (becomes an error in ADR 2.2)',
  },
  'nlgov:query-keys-camel-case': {
    severity: 'warn',
    message: '{{value}} is not lower camelCase. (becomes an error in ADR 2.2)',
    given: ['$.paths.*.*.parameters[?(@.in==\'query\')]', '$.components.securitySchemes[?(@.in==\'query\')]'],
    then: {
      function: pattern,
      field: 'name',
      functionOptions: {
        match: '^\\$?[a-z][a-z\\d]*([A-Z][a-z\\d]*)*$',
      },
    },
  },
  'nlgov:problem-schema-members': {
    severity: 'warn',
    message: '{{error}}. These fields are required: status, title and detail. (becomes an error in ADR 2.2)',
    given: '$..[responses][?(@property && @property.match(/(4|5)\\d\\d/))].content[?(@property=="application/problem+json" || @property=="application/problem+xml")]..schema',
    then: {
      function: schema,
      functionOptions: {
        schema: {
          type: 'object',
          properties: {
            properties: {
              type: 'object',
              required: ['status', 'title', 'detail'],
            },
          },
        },
      },
    },
  },
  'nlgov:problem-invalid-input': {
    severity: 'warn',
    message: 'GET and DELETE endpoints that have parameters, and all other endpoints must be able to return a 400 response (becomes an error in ADR 2.2)',
    given: ['$.paths..[?( @property.match(/(get)|(delete)/) && @.parameters && @.parameters.length > 0 )]', '$.paths..[?( @property.match(/(put)|(post)|(patch)/))]'],
    then: {
      function: schema,
      functionOptions: {
        schema: {
          type: 'object',
          properties: {
            responses: {
              type: 'object',
              required: ['400'],
            },
          },
        },
      },
    },
  },
  'nlgov:date-time-ensure-timezone': {
    severity: 'warn',
    given: '$..properties[*].format',
    message: 'Use date-time format which includes a timezone (becomes an error in ADR 2.2)',
    then: {
      function: pattern,
      functionOptions: {
        notMatch: '/^date-time-local$/',
      },
    },
  },
  'nlgov:time-without-timezone': {
    severity: 'warn',
    given: '$..properties[*].format',
    message: 'Use time-local format without a timezone (becomes an error in ADR 2.2)',
    then: {
      function: pattern,
      functionOptions: {
        notMatch: '/^time$/',
      },
    },
  },
  'nlgov:specify-format-for-date-and-time': {
    severity: 'warn',
    given: ['$..properties[date,datum]', '$..properties[?(@property && @property.match(/((\\w+D)|(_[dD]))((ate)|(atum))/))]'],
    message: 'Any date field must set \'format\' to \'date\' (becomes an error in ADR 2.2)',
    then: {
      function: schema,
      functionOptions: {
        schema: {
          anyOf: [
            {
              required: ['format'],
            },
            {
              properties: {
                allOf: {
                  type: 'array',
                  items: {
                    required: ['format'],
                  },
                },
              },
              required: ['allOf'],
            },
          ],
        },
      },
    },
  },
  'nlgov:use-date-instead-of-datetime': {
    severity: 'warn',
    given: ['$..properties[date,datum]..format', '$..properties[?(@property && @property.match(/((\\w+D)|(_[dD]))((ate)|(atum))/))]..format'],
    message: 'Field represents a date and therefore must set \'format\' to \'date\' (becomes an error in ADR 2.2)',
    then: {
      function: pattern,
      functionOptions: {
        notMatch: '/^date-time$/',
      },
    },
  },
  'nlgov:semver': {
    severity: 'warn',
    message: 'Version {{value}} is not in semver format. (becomes an error in ADR 2.2)',
    given: '$.info.version',
    then: {
      function: pattern,
      functionOptions: {
        match: '^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$',
      },
    },
  },
};
